### ISSUE TITLE
[Feature Request] Enter selected buffer keybind

### ISSUE THREAD

**Issue by loissascha** [EL-MASTOR/bufferlist.nvim#4]
Hello, 
first of all: awesome work! I really love your plugin :) Had no issues with it after the bugfix from yesterday :+1: 

I hope it's okay for me to post a feature request here, it's just one thing that bothers me slightly so I thought I'd share it.

I wish I could somehow jump into the selected buffer. Like with Enter for example. 
When I work on like 3 or 4 files it's just quicker for me to press j/k followed by enter instead of reading which line number the buffer I wanna jump to is on and then pressing that number. The line number might change when I open/close more buffers so I basically have to check it every time I wanna switch buffer, if I know I want like one of the next 2 buffers I'm already navigating down with j while I read the file names to find out which one I wanna go to. Reading the line number and pressing that key is just one extra step in my brain. 

Not sure if anyone else feels like this (or if you as the maintainer feel like this is a feature you'd like to include) but I figured I'd share my thoughts about that

**Comment by EL-MASTOR** [comment]
> Hello, first of all: awesome work! I really love your plugin :) Had no issues with it after the bugfix from yesterday 👍
> 
> I hope it's okay for me to post a feature request here, it's just one thing that bothers me slightly so I thought I'd share it.
> 
> I wish I could somehow jump into the selected buffer. Like with Enter for example. When I work on like 3 or 4 files it's just quicker for me to press j/k followed by enter instead of reading which line number the buffer I wanna jump to is on and then pressing that number. The line number might change when I open/close more buffers so I basically have to check it every time I wanna switch buffer, if I know I want like one of the next 2 buffers I'm already navigating down with j while I read the file names to find out which one I wanna go to. Reading the line number and pressing that key is just one extra step in my brain.
> 
> Not sure if anyone else feels like this (or if you as the maintainer feel like this is a feature you'd like to include) but I figured I'd share my thoughts about that

Hello. Thank you so much for taking effort to suggest new features for the plugin. 
The plugin is intentionally built without the support for the `<Enter>` keymap because I think it's a slow approach to navigate between buffers, since you'll manually take the cursor to the desired line number, which defies one of the principles of the plugin, (few key strokes as possible). To adapt, try not pressing j/k, and just use your eyes to quickly pinpoint the buffer name. Once you do, figuring out the line number happens in a split of a second. This how I personally feel like, and most likely how many people feel like.
**HOWEVER**, if you really don't like that, and want to use the `<Enter>` keymap. You can use a configuration setting which I will provide. This setting will add more freedom to the users and allow them to assign new keymaps of their own to operate on the buffers in the bufferlist window. Yes, users will be able to do stuff such as:
- assign `<Enter>` keymap to switch buffers
- open the buffer in a split window

And many more. This feature will be available in the next update in a few days, so stay tuned.

Thanks a lot for the suggestion. Your suggestion made me come up with this idea.
Thank you again, and if you have any awesome ideas, please let me know. I appreciate every suggestion. Have a great day, and enjoy bufferlist😅

**Comment by EL-MASTOR** [comment]
> Hello, first of all: awesome work! I really love your plugin :) Had no issues with it after the bugfix from yesterday 👍
> 
> I hope it's okay for me to post a feature request here, it's just one thing that bothers me slightly so I thought I'd share it.
> 
> I wish I could somehow jump into the selected buffer. Like with Enter for example. When I work on like 3 or 4 files it's just quicker for me to press j/k followed by enter instead of reading which line number the buffer I wanna jump to is on and then pressing that number. The line number might change when I open/close more buffers so I basically have to check it every time I wanna switch buffer, if I know I want like one of the next 2 buffers I'm already navigating down with j while I read the file names to find out which one I wanna go to. Reading the line number and pressing that key is just one extra step in my brain.
> 
> Not sure if anyone else feels like this (or if you as the maintainer feel like this is a feature you'd like to include) but I figured I'd share my thoughts about that

The update is ready. You can now define your own keymaps to further customize BufferList to your liking with `win_keymaps` & `bufs_keymaps` options. The readme has an example of defining enter keymap, you can copy paste it from there. This update also includes toggling and showing the relative path first via `toggle_path` & `show_path` options.

**Comment by i3d** [comment]
Having the line number hint is great, but I think we also DO have to consider another principle of vim that 'you should not move your fingers out of the home-row as much as possible'. So there are individual setup like hyper-key, there are keyboards that are 60%, 65% or even 40% that don't have the number row, etc... Having a way to invoke `execution` without hitting a number row or number pad is still very much a welcome improvement. Thanks!

**Comment by EL-MASTOR** [comment]
> Having the line number hint is great, but I think we also DO have to consider another principle of vim that 'you should not move your fingers out of the home-row as much as possible'. So there are individual setup like hyper-key, there are keyboards that are 60%, 65% or even 40% that don't have the number row, etc... Having a way to invoke `execution` without hitting a number row or number pad is still very much a welcome improvement. Thanks!

Somebody did suggest replacing the line number keymaps with letters instead and remap the actions keymaps (for closing and saving buffers, etc) to numbers, or something else. But I am reluctant to change BufferList that way. I don't know the situation of every user or if that's gonna improve the user experience, or their productivity.
