### ISSUE TITLE
Error executing vim.schedule

### ISSUE THREAD

**Issue by AB10110F** [EL-MASTOR/bufferlist.nvim#6]
I'm getting this error every time I open bufferlist
I'm using Neovim 0.10.2 on Windows 10

![image](https://github.com/user-attachments/assets/3a2a46bb-f52c-4302-ae22-86868b401980)

**Comment by EL-MASTOR** [comment]
> I'm getting this error every time I open bufferlist I'm using Neovim 0.10.2 on Windows 10
> 
> ![image](https://private-user-images.githubusercontent.com/57847167/386470276-3a2a46bb-f52c-4302-ae22-86868b401980.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTM4NzQsIm5iZiI6MTczMTY1MzU3NCwicGF0aCI6Ii81Nzg0NzE2Ny8zODY0NzAyNzYtM2EyYTQ2YmItZjUyYy00MzAyLWFlMjItODY4NjhiNDAxOTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA2NTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYjViMjVkMjliZmQxM2U5YzNkMmNlMGM4ZmZlYjkxYzgyYzgxYjAzYmY0YzllZjMyNTkxODEyYWUxMmFiNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ATD5EI7FcnuOPN9hKLB_ynxminhmDR-VW_s9SPlla38)

HI, thank you for using bufferlist.nvim 
This error is caused by attempting to execute [realpath](https://www.gnu.org/software/coreutils/manual/html_node/realpath-invocation.html#realpath-invocation) shell command by vim.system which required for generating relative paths, please install it and try again, I'm hoping BufferList will make your work your neovim work easier and more enjoyable.
If the error proceeds, or if you have any issues or awesome ideas, please do let me know. Feedback is always welcome.

**Comment by EL-MASTOR** [comment]
> Thanks for the quick response I was checking realpath but it seems that it is not available on windows, I want to clarify that I'm not using WSL, I use neovim with powershell, in case you plan to make it a multi-platform, I think the alternative for powershell is Resolve-Path

Hi, I'm sorry for the late response, I don't have contigues internet access these days.
Thanks for the helpful feedback.
I updated the plugin, so that it uses the output from `vim.fn.expand("#"..buffer..":~:.:h")` in case `realpath` doesn't exist. I havn't tested it on windows, but I think I would work.
Thank you again for feedback, and for checking out BufferList. Have a nice day. And if you have any suggestion or an issue, please report them, I appreciate every help.

**Comment by AB10110F** [comment]
> > Thanks for the quick response I was checking realpath but it seems that it is not available on windows, I want to clarify that I'm not using WSL, I use neovim with powershell, in case you plan to make it a multi-platform, I think the alternative for powershell is Resolve-Path
> 
> Hi, I'm sorry for the late response, I don't have contigues internet access these days. Thanks for the helpful feedback. I updated the plugin, so that it uses the output from `vim.fn.expand("#"..buffer..":~:.:h")` in case `realpath` doesn't exist. I havn't tested it on windows, but I think I would work. Thank you again for the feedback, and for checking out BufferList. Have a nice day. And if you have any suggestion or an issue, please report them, I appreciate every help.

That worked. Thanks.

**Comment by EL-MASTOR** [comment]
Good to know that, enjoy
